language: objective-c
osx_image: xcode7.3
xcode_project: TestFramework.xcodeproj
xcode_scheme: TestFramework
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- carthage build --no-skip-current
